# Generated by Django 2.1.4 on 2018-12-26 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 18, 41, 12, 446876, tzinfo=utc)),
        ),
    ]
