# Generated by Django 2.1.4 on 2018-12-26 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20181226_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uploadDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 18, 42, 13, 130380, tzinfo=utc)),
        ),
    ]
