# Generated by Django 2.1.4 on 2018-12-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_auto_20181226_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_path',
            field=models.CharField(default='static/memes/posts/default.jpg', max_length=200),
        ),
    ]
