# Generated by Django 2.1.4 on 2018-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_post_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_path',
            field=models.CharField(default='/default.jpg', max_length=200),
        ),
    ]
