# Generated by Django 2.1.4 on 2018-12-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0006_auto_20181226_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_path',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='static/memes/posts/default.jpg', upload_to=''),
        ),
    ]
