# Generated by Django 2.1.4 on 2019-01-01 21:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0014_auto_20190101_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='reactiontype',
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='memes.Post'),
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
